server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: accounts
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/cuentas/**
        - id: movements
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/movimientos/**
        - id: clients
          uri: lb://USER-SERVICE
          predicates:
            - Path=/clientes/**
        - id: banking
          uri: lb://USER-SERVICE
          predicates:
            - Path=/banking/**
        - id: reports
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/reportes/**

eureka:
  client:
    register-with-eureka: false
