server:
  port: 8090

spring:
  application:
    name: transaction-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_db
    username: root
    password: 230011
  jackson:
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  kafka:
    template:
      default-topic: transactionTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: transactionId
      properties:
        spring:
          json:
            type:
              mapping: com.microservices.domains.dto.MovementPSTRs:com.microservices.domains.dto.MovementPSTRq
            trusted:
              packages: com.microservices
      bootstrap-servers: localhost:9092

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka